apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: airlinedb
  namespace: schemahero-tutorial
spec:
  schemahero:
    image: "localhost:32000/schemahero/schemahero"
  immediateDeploy: false
  connection:
    postgres:
      uri:
        value: postgres://airlinedb-user:password@10.43.104.235:5432/airlinedb?sslmode=disable

